'use strict';

// Check 1: what the jump-fit rule (J) takes away that might be real.
//
// Matched v2 occlusions that J stops calling occlusion, where the truth edge
// they matched is a SILHOUETTE or BOUNDARY -- an edge that should have a depth
// step. (The ones matching crease truth are the expected case: a fold, read as
// a step by plane extrapolation.) Same three panels as 09-12's sheets: picture
// with truth and explain's sample points | normal pass | depth-step map.
//
//   node 03-crops.js [set ...]      sheets/<set>-<n>.png, sheets/INDEX.md

const fs = require('node:fs');
const path = require('node:path');
const { SETS, read, drawSheets } = require('./lib');

const T = 0.02;
const lg = (a, b) => Math.log2(Math.max(a, 1e-9) / Math.max(b, 1e-9));
const realStep = (r) => r.raw1 >= T && r.raw8 / Math.max(r.raw1, 1e-9) < 2;
const SHEETS = path.join(__dirname, 'sheets');

const sets = process.argv.length > 2 ? process.argv.slice(2) : ['helmet-256', 'helmet-512'];
const row = (file, i, r) =>
  `| ${file} | ${i} | ${r.view} | ${r.id} | ${r.truthCause} | ${r.length.toFixed(1)} | ${r.jump.toFixed(3)} | ` +
  `${r.breakAt === null ? '-' : r.breakAt.toFixed(1)} | ${[1.25, 2.5, 5].map((o) => r.ex[o].toFixed(3)).join(' / ')} | ` +
  `${lg(r.ex[2.5], r.ex[1.25]).toFixed(2)} / ${lg(r.ex[5], r.ex[2.5]).toFixed(2)} | ${(r.raw8 / Math.max(r.raw1, 1e-9)).toFixed(2)} | ` +
  `${realStep(r) ? '**yes**' : 'no'} | ${r.matchDistance.toFixed(1)} / ${r.matchAngle.toFixed(0)}° |`;
const index = [
  '# Contact sheets: matched occlusions the jump-fit rule would reclassify',
  '',
  'Generated by `03-crops.js`. Only those whose matched truth edge is a silhouette or boundary.',
  'Panels: picture + truth + samples | normal pass | depth-step map.',
  'Cyan = visible occluding truth, magenta = hidden occluding truth, faint white = visible crease truth,',
  'red = the detection, yellow = explain\'s sample pairs.',
  '',
  '`growth` is depthStep at offset 8 over offset 1; under 2 with >= 2 cm at offset 1 is a real step by 09-10\'s test.',
  '',
  '| sheet | row | view | id | truth | length | jump h (m) | break at (px) | excess @1.25 / 2.5 / 5 (m) | exponents | growth | real step? | match px / ° |',
  '|---|---|---|---|---|---|---|---|---|---|---|---|---|',
];
for (const set of sets) {
  const rows = read(`${set}.json`)
    .filter((r) => r.role === 'hit' && r.ex[2.5] >= T && r.jump < T && (r.truthCause === 'silhouette' || r.truthCause === 'boundary'))
    .sort((a, b) => a.view.localeCompare(b.view) || a.id - b.id);
  for (const { file, rows: chunk } of drawSheets(set, rows, set, 6, SHEETS)) {
    chunk.forEach((r, i) => index.push(row(file, i, r)));
    console.log(`sheets/${file}  ${chunk.length} rows`);
  }
  console.log(`${set}: ${rows.length} detections, ${rows.filter(realStep).length} real steps by the growth test`);

  // And the real steps -- by the growth test, whatever they matched -- that J would lose.
  const lost = read(`${set}.json`)
    .filter((r) => r.role === 'hit' && r.ex[2.5] >= T && r.jump < T && realStep(r))
    .sort((a, b) => a.view.localeCompare(b.view) || a.id - b.id);
  for (const { file, rows: chunk } of drawSheets(set, lost, `${set}-lost-real-steps`, 6, SHEETS)) {
    chunk.forEach((r, i) => index.push(row(file, i, r)));
    console.log(`sheets/${file}  ${chunk.length} rows`);
  }
}
fs.writeFileSync(path.join(SHEETS, 'INDEX.md'), `${index.join('\n')}\n`);
