'use strict';

// Contact sheets of the 88, one row per detection, three panels:
//
//   1. the picture (faded), with occluding truth -- visible cyan, hidden
//      magenta -- visible crease truth in faint white, the detection in red
//      and explain's sample pairs in yellow
//   2. the normal pass, detection in red
//   3. a depth-step map: each pixel's largest 4-neighbour depth difference,
//      log grey from 1 mm (black) to 1 m (white), with occluding truth and
//      the detection
//
// 36 x 36 source pixels around the detection's midpoint, at 7x.
//
//   sheets/<tier>-<n>.png   sheets/INDEX.md   (which detection is on which row)

const fs = require('node:fs');
const path = require('node:path');
const { REPO, loadView, read } = require('./load');
const { encodePNG } = require(`${REPO}/scripts/png`);
const { crossings, DEFAULTS } = require(`${REPO}/src/lab/explain`);
const { MIN_VISIBLE } = require(`${REPO}/src/lab/match`);

const WIN = 36, S = 7, P = WIN * S, GAP = 6;
// Rows per sheet, chosen so each sheet stays readable at a glance.
const TIERS = [['A1', 4], ['A2', 6], ['B', 8], ['C', 6]];
const SHEETS = path.join(__dirname, 'sheets');

const classified = read('classified.json');
const views = new Map();
const view = (n) => { if (!views.has(n)) views.set(n, loadView(n)); return views.get(n); };

function put(c, x, y, col, a = 1) {
  x = Math.round(x); y = Math.round(y);
  if (x < 0 || y < 0 || x >= c.width || y >= c.height) return;
  const o = (y * c.width + x) * 4;
  for (let k = 0; k < 3; k++) c.px[o + k] = c.px[o + k] * (1 - a) + col[k] * a;
  c.px[o + 3] = 255;
}

function line(c, ox, oy, clip, x0, y0, x1, y1, col, a = 1, r = 0) {
  const n = Math.max(2, Math.ceil(Math.hypot(x1 - x0, y1 - y0) * 2));
  for (let i = 0; i <= n; i++) {
    const x = x0 + (x1 - x0) * i / n, y = y0 + (y1 - y0) * i / n;
    if (x < 0 || y < 0 || x >= clip || y >= clip) continue;
    for (let dy = -r; dy <= r; dy++) for (let dx = -r; dx <= r; dx++) put(c, ox + x + dx, oy + y + dy, col, a);
  }
}

function drawRow(c, r, oy) {
  const v = view(r.view);
  const cx = Math.round((r.x0 + r.x1) / 2) - WIN / 2, cy = Math.round((r.y0 + r.y1) / 2) - WIN / 2;
  const { beauty, rasters } = v;
  const D = rasters.depth, N = rasters.normal, w = beauty.width;
  for (let py = 0; py < P; py++) for (let px = 0; px < P; px++) {
    const sx = cx + Math.floor(px / S), sy = cy + Math.floor(py / S);
    if (sx < 0 || sy < 0 || sx >= w || sy >= w) continue;
    const i = sy * w + sx;
    put(c, px, oy + py, [beauty.px[i * 4], beauty.px[i * 4 + 1], beauty.px[i * 4 + 2]].map((q) => q * 0.8));
    put(c, P + GAP + px, oy + py, [N.data[i * 4], N.data[i * 4 + 1], N.data[i * 4 + 2]].map((q) => q * 255));
    let m = 0;
    for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
      const qx = sx + dx, qy = sy + dy;
      if (qx < 0 || qy < 0 || qx >= w || qy >= w) continue;
      m = Math.max(m, Math.abs(D.data[i] - D.data[qy * w + qx]));
    }
    const g = Math.max(0, Math.min(1, (Math.log10(m + 1e-4) + 3) / 3)) * 255;
    put(c, 2 * (P + GAP) + px, oy + py, [g, g, g]);
  }
  for (const e of v.slots.get('T')) {
    if (e.type !== 'gt-edge') continue;
    const occl = e.cause !== 'crease', vis = e.visible >= MIN_VISIBLE;
    const col = occl ? (vis ? [0, 230, 255] : [255, 0, 200]) : (vis ? [255, 255, 255] : null);
    if (!col) continue;
    const a = occl ? 1 : 0.45;
    const X0 = (e.x0 - cx) * S, Y0 = (e.y0 - cy) * S, X1 = (e.x1 - cx) * S, Y1 = (e.y1 - cy) * S;
    line(c, 0, oy, P, X0, Y0, X1, Y1, col, a);
    if (occl) line(c, 2 * (P + GAP), oy, P, X0, Y0, X1, Y1, col, a);
  }
  for (const ox of [0, P + GAP, 2 * (P + GAP)]) {
    line(c, ox, oy, P, (r.x0 - cx) * S, (r.y0 - cy) * S, (r.x1 - cx) * S, (r.y1 - cy) * S, [255, 40, 40], 1, 1);
  }
  for (const [a, b] of crossings(r, DEFAULTS)) {
    for (const p of [a, b]) line(c, 0, oy, P, (p.x - cx) * S, (p.y - cy) * S, (p.x - cx) * S, (p.y - cy) * S, [255, 230, 0], 1, 1);
  }
}

fs.mkdirSync(SHEETS, { recursive: true });
const index = [
  '# Contact sheets: the 88',
  '',
  'Generated by `10-crops.js`; see `../README.md` and `../../2026-09-12.md`.',
  'Panels: picture + truth + samples | normal pass | depth-step map.',
  'Cyan = visible occluding truth, magenta = hidden occluding truth, faint white = visible crease truth,',
  'red = the detection, yellow = explain\'s sample pairs.',
  '',
  '| sheet | row | view | id | tier | length | jump h (m) | depthExcess (m) | normalStep | match px / ° | occluding truth |',
  '|---|---|---|---|---|---|---|---|---|---|---|',
];
for (const [tier, perSheet] of TIERS) {
  const rows = classified.filter((r) => r.tier.startsWith(tier))
    .sort((a, b) => a.view.localeCompare(b.view) || a.id - b.id);
  for (let start = 0, sheet = 0; start < rows.length; start += perSheet, sheet++) {
    const chunk = rows.slice(start, start + perSheet);
    const c = { width: 3 * P + 2 * GAP, height: chunk.length * P + (chunk.length - 1) * GAP };
    c.px = Buffer.alloc(c.width * c.height * 4, 255);
    const file = `${tier}-${sheet}.png`;
    chunk.forEach((r, row) => {
      drawRow(c, r, row * (P + GAP));
      index.push(`| ${file} | ${row} | ${r.view} | ${r.id} | ${r.tier} | ${r.length.toFixed(1)} | ${r.jump.toFixed(3)} | ` +
        `${r.depthExcess.toFixed(3)} | ${r.normalStep.toFixed(0)}° | ${r.matchDistance.toFixed(1)} / ${r.matchAngle.toFixed(0)}° | ${r.occ} |`);
    });
    fs.writeFileSync(path.join(SHEETS, file), encodePNG(c.width, c.height, c.px));
    console.log(`sheets/${file}  ${chunk.length} rows`);
  }
}
fs.writeFileSync(path.join(SHEETS, 'INDEX.md'), `${index.join('\n')}\n`);
console.log('sheets/INDEX.md');
